//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int IdAttendance { get; set; }
        public int IdStaff { get; set; }
        public int IdShifts { get; set; }
        public int IdStatusAttendance { get; set; }
    
        public virtual Shifts Shifts { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StatusAttendance StatusAttendance { get; set; }
    }
}
