//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFUIKitProfessional.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLogs
    {
        public int IdTimeLogs { get; set; }
        public int IdStaff { get; set; }
        public int StartLog { get; set; }
        public int EndLog { get; set; }
        public int HouseWorked { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
